<?php

declare(strict_types=1);

namespace Mustache;

use Psr\Log\LoggerInterface;

/**
 * Mustache Cache interface.
 *
 * Interface for caching and loading \Mustache\Template classes
 * generated by the \Mustache\Compiler.
 */
interface Cache
{
    /**
     * Load a compiled \Mustache\Template class from cache.
     *
     * @return bool indicates successfully class load
     */
    public function load(string $key): bool;

    /**
     * Mustache\Cache and load a compiled \Mustache\Template class.
     */
    public function cache(string $key, string $value): void;

    public function setLogger(?LoggerInterface $logger = null): void;
}
